[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Content-Type = "font/woff2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 